In [8]:
#Create a 5x5 matrix with row values ranging from 0 to 4


import numpy as np

matrix = np.zeros((5,5))
print("creating matrix 5x5:")
print(matrix)
print("updating row values ranging from 0 to 4.")
matrix += np.arange(5)
print(matrix)




creating matrix 5x5:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
updating row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [19]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

x = np.random.random((5,3))
print("First matrix: \n", x)

y = np.random.random((3,2))
print("Second matrix: \n",y)

mult_matrix = np.dot(x, y)
print("Result of multiplication of x and y: \n", mult_matrix)








First matrix: 
 [[0.32925886 0.21781875 0.4095749 ]
 [0.44119642 0.8724831  0.45402368]
 [0.87861032 0.98696992 0.84015815]
 [0.28542717 0.24530338 0.75950495]
 [0.91156493 0.77340495 0.6292721 ]]
Second matrix: 
 [[0.91915385 0.60700568]
 [0.03669241 0.78917596]
 [0.3232952  0.82537019]]
Result of multiplication of x and y: 
 [[0.44304544 0.70981023]
 [0.58432456 1.33108903]
 [1.11541145 2.00565587]
 [0.51689656 0.99371619]
 [1.06968715 1.68306011]]


● What is the result of the following expression?
● 0 * np.nan  : **nan**
● np.nan == np.nan : **false**
● np.inf > np.nan  :**false**
● np.nan - np.nan  : **nan**
● np.nan in set([np.nan])  :**true**
● 0.3 == 3 * 0.1 : **false**


In [31]:
#Create a 10x10 array with random values and find the minimum and maximum values

array=np.random.random((10,10))
print (array)


max_value=array.max()
print("The maximum value in array is: ", max_value)

min_value=array.min()
print("The minimum value in array is: ", min_value)



[[0.38761914 0.49862411 0.5387489  0.04309208 0.6969067  0.79451538
  0.77738348 0.93240047 0.46217378 0.3904501 ]
 [0.8754766  0.57377339 0.0573519  0.50823741 0.22078578 0.41961522
  0.90619403 0.50477687 0.96683449 0.51096826]
 [0.83578737 0.39893002 0.48676294 0.35923803 0.94315685 0.3200654
  0.62989582 0.37277361 0.46167155 0.55661573]
 [0.90226094 0.75755861 0.64115075 0.51323583 0.40855942 0.81281193
  0.5643712  0.04554436 0.25732188 0.48548233]
 [0.0040746  0.17298746 0.43532123 0.45016039 0.17854868 0.91155779
  0.27696808 0.58702654 0.13997322 0.38683901]
 [0.9287668  0.66560589 0.18534662 0.23232483 0.77005313 0.80045508
  0.4105304  0.05330363 0.77975999 0.59344868]
 [0.34375903 0.65175017 0.21261473 0.19684052 0.85795172 0.84948475
  0.95834805 0.89173461 0.77604039 0.74708816]
 [0.79378422 0.5866047  0.68582925 0.33463109 0.74649707 0.74065986
  0.26573553 0.30994704 0.44231744 0.97544059]
 [0.88610428 0.55353449 0.78638872 0.15121    0.57773556 0.85945839
  0.30480487 

In [36]:
#Create a null vector of size 10 but the fifth value which is 1
x=np.zeros((10))
print(x)

x[5]=1

print("array:", x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
